#!/usr/bin/env python3
"""
Bay State Scraper - Runner Setup CLI

Standalone script for setting up a scraper runner via Docker Compose.
Requires: Docker and Docker Compose (v2)

Usage:
    curl -sSL https://raw.githubusercontent.com/Bay-State-Pet-and-Garden-Supply/BayStateScraper/main/install.py | python3
"""

import os
import subprocess
import sys
import platform
import urllib.request
from pathlib import Path

# --- Configuration Constants ---
DEFAULT_API_URL = "https://bay-state-app.vercel.app"
REPO_RAW_URL = "https://raw.githubusercontent.com/Bay-State-Pet-and-Garden-Supply/BayStateScraper/main"
DOCKER_COMPOSE_URL = f"{REPO_RAW_URL}/docker-compose.yml"

INSTALL_DIR = Path(os.getcwd())  # Install in current directory
ENV_FILE = INSTALL_DIR / ".env"
COMPOSE_FILE = INSTALL_DIR / "docker-compose.yml"

def print_header():
    print("=" * 60)
    print("         Bay State Scraper - Runner Setup (Docker)          ")
    print("=" * 60)
    print()

def print_step(msg: str):
    print(f"\n---> {msg}")

def print_success(msg: str):
    print(f"  [✓] {msg}")

def print_error_and_exit(msg: str):
    print(f"\n  [X] ERROR: {msg}")
    print("  Exiting setup.")
    sys.exit(1)

def check_docker_installed():
    """Verify Docker and Docker Compose plugin are available."""
    print_step("Checking prerequisites...")
    try:
        # Check docker
        subprocess.run(
            ["docker", "--version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=True,
            shell=(platform.system() == "Windows")
        )
        print_success("Docker is installed.")
        
        # Check docker compose (v2)
        subprocess.run(
            ["docker", "compose", "version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=True,
            shell=(platform.system() == "Windows")
        )
        print_success("Docker Compose is installed.")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print_error_and_exit(
            "Docker and/or Docker Compose are not installed.\n"
            "      Please install Docker Desktop (Windows/Mac) or Docker Engine (Linux)\n"
            "      from https://docs.docker.com/get-docker/ before continuing."
        )

def get_runner_name() -> str:
    """Generate a default runner name based on hostname."""
    hostname = platform.node().lower().replace(".local", "")
    os_name = platform.system().lower()
    return f"runner-{os_name}-{hostname}"

def prompt_api_key() -> str:
    """Prompt the user for their API key."""
    print_step("Configuration")
    print("  You need a Runner API Key from the BayStateApp Admin Panel.")
    print("  (Go to: Scraper Network > Runner Accounts > Create Runner)")
    print()
    
    while True:
        try:
            api_key = input("  Enter your API Key (starts with bsr_): ").strip()
            if not api_key:
                print("  [!] API Key is required.")
                continue
            if not api_key.startswith("bsr_"):
                print("  [!] Warning: API keys usually start with 'bsr_'. Please verify it.")
                confirm = input("  Use it anyway? [y/N]: ").strip().lower()
                if confirm != 'y':
                    continue
            return api_key
        except (KeyboardInterrupt, EOFError):
            print("\nSetup cancelled.")
            sys.exit(1)
            
    # Default fallback (should not be reached)
    return ""

def create_env_file(api_key: str, runner_name: str):
    """Write the .env file with production configuration."""
    print_step("Generating configuration files...")
    
    env_content = f"""# Bay State Scraper - Runner Configuration
# Generated by install.py

# API Connection
SCRAPER_API_URL={DEFAULT_API_URL}
SCRAPER_API_KEY={api_key}

# Runner Identity
RUNNER_NAME={runner_name}

# Daemon Settings
POLL_INTERVAL=30
MAX_JOBS_BEFORE_RESTART=100
LOG_LEVEL=INFO
"""
    try:
        with open(ENV_FILE, "w") as f:
            f.write(env_content)
        # Try to secure the file if not on Windows
        if platform.system() != "Windows":
            os.chmod(ENV_FILE, 0o600)
        print_success(f"Created {ENV_FILE.name}")
    except Exception as e:
        print_error_and_exit(f"Failed to write .env file: {e}")

def download_docker_compose():
    """Download the production docker-compose.yml if it doesn't exist."""
    if COMPOSE_FILE.exists():
        print_success(f"Found existing {COMPOSE_FILE.name}")
        return

    try:
        req = urllib.request.Request(DOCKER_COMPOSE_URL)
        with urllib.request.urlopen(req, timeout=10) as response:
            content = response.read().decode('utf-8')
            with open(COMPOSE_FILE, "w") as f:
                f.write(content)
        print_success(f"Downloaded {COMPOSE_FILE.name}")
    except Exception as e:
        print_error_and_exit(f"Failed to download docker-compose.yml: {e}")

def start_docker_daemon():
    """Build the image and start the compose stack."""
    print_step("Starting the Scraper Runner daemon...")
    print("  This will build the Docker image (this may take a few minutes).")
    print()
    
    try:
        # Build first
        subprocess.run(
            ["docker", "compose", "build"],
            check=True,
            shell=(platform.system() == "Windows")
        )
        # Then bring it up
        subprocess.run(
            ["docker", "compose", "up", "-d"],
            check=True,
            shell=(platform.system() == "Windows")
        )
        print()
        print_success("Daemon started successfully!")
    except subprocess.CalledProcessError as e:
        print_error_and_exit(f"Failed to start Docker Compose. (Exit code: {e.returncode})")

def main():
    print_header()
    
    # 1. Prereqs
    check_docker_installed()
    
    # 2. Config
    runner_name = get_runner_name()
    api_key = prompt_api_key()
    
    # 3. Files
    create_env_file(api_key, runner_name)
    download_docker_compose()
    
    # 4. Run
    start_docker_daemon()
    
    # 5. Outro
    print("\n" + "=" * 60)
    print("  ✅ Installation Complete!")
    print("=" * 60 + "\n")
    print("  The scraper is now running in the background via Docker.")
    print("  It will automatically connect to Vercel and poll for jobs.")
    print()
    print("  Useful Commands:")
    print("    • View logs:    docker compose logs -f")
    print("    • Stop runner:  docker compose down")
    print("    • Update:       docker compose pull && docker compose up -d")
    print()

if __name__ == "__main__":
    main()
