"""Tests for config migration normalization."""

import sys
from pathlib import Path

# Add tools directory to path for imports
_tools_path = Path(__file__).resolve().parent.parent.parent / "tools"
if str(_tools_path) not in sys.path:
    sys.path.insert(0, str(_tools_path))

import pytest
import yaml

from migrate_configs import ConfigNormalizer, MigrationResult


class TestConfigNormalizer:
    """Tests for ConfigNormalizer class."""

    def test_load_valid_yaml(self, tmp_path: Path) -> None:
        """Test loading a valid YAML file."""
        yaml_content = {
            "name": "test-scraper",
            "base_url": "https://example.com",
            "selectors": [{"name": "Title", "selector": "h1"}],
        }
        yaml_file = tmp_path / "test-scraper.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        assert normalizer.load() is True
        assert normalizer.yaml_data == yaml_content

    def test_load_nonexistent_file(self) -> None:
        """Test loading a nonexistent file."""
        normalizer = ConfigNormalizer(Path("/nonexistent/scraper.yaml"))
        assert normalizer.load() is False
        assert "File not found" in normalizer.errors[0]

    def test_load_invalid_yaml(self, tmp_path: Path) -> None:
        """Test loading an invalid YAML file."""
        yaml_file = tmp_path / "invalid.yaml"
        yaml_file.write_text("invalid: yaml: content: [[[")

        normalizer = ConfigNormalizer(yaml_file)
        assert normalizer.load() is False
        assert len(normalizer.errors) > 0

    def test_normalize_adds_schema_version(self, tmp_path: Path) -> None:
        """Test that normalization adds schema_version."""
        yaml_content = {
            "name": "test-scraper",
            "base_url": "https://example.com",
        }
        yaml_file = tmp_path / "test.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        assert "schema_version" in normalized
        assert normalized["schema_version"] == "1.0"

    def test_normalize_copies_required_fields(self, tmp_path: Path) -> None:
        """Test that normalization copies required fields."""
        yaml_content = {
            "name": "my-scraper",
            "base_url": "https://mysite.com",
        }
        yaml_file = tmp_path / "my-scraper.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        assert normalized["name"] == "my-scraper"
        assert normalized["base_url"] == "https://mysite.com"

    def test_normalize_applies_defaults(self, tmp_path: Path) -> None:
        """Test that normalization applies default values for missing optional fields."""
        yaml_content = {
            "name": "minimal-scraper",
            "base_url": "https://example.com",
        }
        yaml_file = tmp_path / "minimal.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        assert normalized["timeout"] == 30
        assert normalized["retries"] == 3
        assert normalized["image_quality"] == 50
        assert normalized["selectors"] == []
        assert normalized["workflows"] == []
        assert normalized["test_skus"] == []
        assert normalized["fake_skus"] == []

    def test_normalize_preserves_existing_values(self, tmp_path: Path) -> None:
        """Test that existing values are preserved during normalization."""
        yaml_content = {
            "name": "custom-scraper",
            "base_url": "https://custom.com",
            "timeout": 60,
            "retries": 5,
            "image_quality": 90,
            "test_skus": ["SKU001", "SKU002"],
            "selectors": [{"name": "Price", "selector": ".price"}],
        }
        yaml_file = tmp_path / "custom.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        assert normalized["timeout"] == 60
        assert normalized["retries"] == 5
        assert normalized["image_quality"] == 90
        assert normalized["test_skus"] == ["SKU001", "SKU002"]
        assert len(normalized["selectors"]) == 1

    def test_normalize_generates_display_name(self, tmp_path: Path) -> None:
        """Test that display_name is optional and can be generated by caller."""
        yaml_content = {
            "name": "my-test-scraper",
            "base_url": "https://example.com",
        }
        yaml_file = tmp_path / "display-test.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        # display_name should be None (not auto-generated in normalizer)
        # The UI or caller can generate a display name from the slug
        assert "display_name" in normalized
        assert normalized["display_name"] is None

    def test_normalize_missing_name_error(self, tmp_path: Path) -> None:
        """Test that missing name field produces an error."""
        yaml_content = {
            "base_url": "https://example.com",
        }
        yaml_file = tmp_path / "no-name.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        assert "Missing required field: name" in normalizer.errors

    def test_normalize_missing_base_url_error(self, tmp_path: Path) -> None:
        """Test that missing base_url field produces an error."""
        yaml_content = {
            "name": "test-scraper",
        }
        yaml_file = tmp_path / "no-url.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()

        assert "Missing required field: base_url" in normalizer.errors

    def test_validate_valid_config(self, tmp_path: Path) -> None:
        """Test validation of a valid config."""
        yaml_content = {
            "name": "valid-scraper",
            "base_url": "https://valid.com",
            "timeout": 30,
            "retries": 3,
            "image_quality": 50,
            "selectors": [
                {"name": "Title", "selector": "h1", "attribute": "text"},
            ],
        }
        yaml_file = tmp_path / "valid.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()
        valid, errors = normalizer.validate(normalized)

        # Validation passes (either with full validation or skipped validation)
        assert valid is True
        # If there are errors, they should be warnings (schema validation skipped)
        for error in errors:
            assert "WARNING" in error or "Schema validation skipped" in error


class TestScraperConfigValidation:
    """Unit tests for ScraperConfig schema validation."""

    def test_validate_invalid_timeout(self) -> None:
        """Test validation fails for out-of-bounds timeout."""
        from scraper_backend.scrapers.models.config import ScraperConfig, SelectorConfig

        with pytest.raises(Exception):  # pydantic ValidationError
            ScraperConfig(
                schema_version="1.0",
                name="bad-timeout",
                base_url="https://example.com",
                timeout=500,  # Max is 300
                selectors=[SelectorConfig(name="test", selector="h1")],
            )

    def test_validate_selector_without_name(self) -> None:
        """Test validation fails for selector without name."""
        from scraper_backend.scrapers.models.config import ScraperConfig, SelectorConfig

        with pytest.raises(Exception):  # pydantic ValidationError
            ScraperConfig(
                schema_version="1.0",
                name="no-selector-name",
                base_url="https://example.com",
                selectors=[
                    SelectorConfig(selector="h1"),  # Missing 'name'
                ],
            )

    def test_validate_valid_config(self) -> None:
        """Test validation passes for valid config."""
        from scraper_backend.scrapers.models.config import ScraperConfig, SelectorConfig

        config = ScraperConfig(
            schema_version="1.0",
            name="valid-scraper",
            base_url="https://example.com",
            timeout=30,
            selectors=[
                SelectorConfig(name="product_title", selector="h1.title"),
                SelectorConfig(name="price", selector="span.price", attribute="text"),
            ],
        )

        assert config.name == "valid-scraper"
        assert config.base_url == "https://example.com"
        assert len(config.selectors) == 2

    def test_validate_unknown_schema_version(self) -> None:
        """Test validation fails for unknown schema version."""
        from scraper_backend.scrapers.models.config import ScraperConfig, SelectorConfig

        with pytest.raises(Exception):  # pydantic ValidationError
            ScraperConfig(
                schema_version="99.0",  # Unknown version
                name="test",
                base_url="https://example.com",
                selectors=[SelectorConfig(name="test", selector="h1")],
            )


class TestMigrationResult:
    """Tests for MigrationResult class."""

    def test_result_initialization(self, tmp_path: Path) -> None:
        """Test MigrationResult initializes correctly."""
        yaml_file = tmp_path / "test.yaml"
        yaml_file.write_text(yaml.dump({"name": "test", "base_url": "https://example.com"}))

        result = MigrationResult(yaml_file)

        assert result.yaml_path == yaml_file
        assert result.slug == "test"
        assert result.success is False
        assert len(result.errors) == 0
        assert result.config_id is None
        assert result.version_id is None


class TestIntegration:
    """Integration tests for migration pipeline."""

    def test_full_migration_pipeline(self, tmp_path: Path) -> None:
        """Test complete migration pipeline: load -> normalize -> validate."""
        yaml_content = {
            "name": "integration-test",
            "base_url": "https://integration.example.com",
            "display_name": "Integration Test",
            "timeout": 45,
            "retries": 2,
            "image_quality": 75,
            "selectors": [
                {"name": "Product", "selector": ".product", "attribute": "text"},
                {"name": "Price", "selector": ".price", "attribute": "text"},
            ],
            "workflows": [
                {
                    "action": "navigate",
                    "params": {"url": "https://example.com/search?q={sku}"},
                },
                {"action": "wait", "params": {"seconds": 5}},
                {"action": "extract", "params": {"fields": ["Product", "Price"]}},
            ],
            "test_skus": ["TEST123"],
            "fake_skus": ["FAKE456"],
            "edge_case_skus": ["EDGE"],
        }
        yaml_file = tmp_path / "integration-test.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        # Run through normalizer
        normalizer = ConfigNormalizer(yaml_file)
        assert normalizer.load() is True

        normalized = normalizer.normalize()
        assert "schema_version" in normalized
        assert normalized["schema_version"] == "1.0"
        assert normalized["name"] == "integration-test"
        assert normalized["display_name"] == "Integration Test"
        assert normalized["timeout"] == 45

        valid, errors = normalizer.validate(normalized)
        assert valid is True
        # If there are errors, they should be warnings (schema validation skipped)
        for error in errors:
            assert "WARNING" in error or "Schema validation skipped" in error

    def test_minimal_config_migration(self, tmp_path: Path) -> None:
        """Test migration of minimal valid config."""
        yaml_content = {
            "name": "minimal",
            "base_url": "https://minimal.com",
        }
        yaml_file = tmp_path / "minimal.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()
        valid, errors = normalizer.validate(normalized)

        assert valid is True
        assert normalized["schema_version"] == "1.0"
        assert normalized["timeout"] == 30  # Default applied
        assert normalized["retries"] == 3  # Default applied

    def test_complex_amazon_like_config(self, tmp_path: Path) -> None:
        """Test migration of a complex Amazon-like config."""
        yaml_content = {
            "name": "amazon",
            "display_name": "Amazon",
            "base_url": "https://www.amazon.com",
            "timeout": 15,
            "retries": 2,
            "image_quality": 100,
            "selectors": [
                {"name": "Name", "selector": "#productTitle", "attribute": "text"},
                {"name": "Brand", "selector": "#bylineInfo", "attribute": "text"},
                {
                    "name": "Images",
                    "selector": "#altImages li.imageThumbnail img",
                    "attribute": "src",
                    "multiple": True,
                },
            ],
            "workflows": [
                {
                    "action": "conditional_click",
                    "params": {"selector": "#sp-cc-accept"},
                },
                {
                    "action": "navigate",
                    "params": {"url": "https://www.amazon.com/s?k={sku}"},
                },
                {"action": "wait", "params": {"seconds": 5}},
            ],
            "test_skus": ["035585499741", "079105116708"],
            "fake_skus": ["xyzabc123notexist456"],
            "edge_case_skus": ["A1", "ABCDEFGHIJKLMNOPQRSTUVWXYZ"],
            "anti_detection": {
                "enable_captcha_detection": False,
                "enable_rate_limiting": False,
                "enable_human_simulation": False,
                "enable_session_rotation": False,
                "enable_blocking_handling": False,
                "rate_limit_min_delay": 1.0,
                "rate_limit_max_delay": 3.0,
                "session_rotation_interval": 100,
                "max_retries_on_detection": 3,
            },
            "validation": {
                "no_results_selectors": [".s-no-results-filler", "#noResultsTitle"],
                "no_results_text_patterns": ["no results for", "0 results for"],
            },
        }
        yaml_file = tmp_path / "amazon.yaml"
        yaml_file.write_text(yaml.dump(yaml_content))

        normalizer = ConfigNormalizer(yaml_file)
        normalizer.load()
        normalized = normalizer.normalize()
        valid, errors = normalizer.validate(normalized)

        assert valid is True
        assert normalized["schema_version"] == "1.0"
        assert len(normalized["selectors"]) == 3
        assert len(normalized["workflows"]) == 3
        assert normalized["anti_detection"]["enable_captcha_detection"] is False
